version: '3.9'
services:
  java-app:
    image: docker-backbone:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-backbone
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - java-app